# Generated by Django 3.2.7 on 2021-11-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
