# Generated by Django 3.2.7 on 2021-11-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_user_profile_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='name',
            new_name='user',
        ),
    ]
