# Generated by Django 3.2.7 on 2021-11-30 17:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.TextField(default='default', verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default=datetime.date(2021, 11, 30))),
                ('order_state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_name', models.TextField(max_length=20)),
                ('arm_price', models.FloatField(default=0.0)),
                ('arm_origin', models.TextField(max_length=20)),
                ('arm_calibre', models.TextField(max_length=20)),
                ('arm_capacity', models.IntegerField(null=True)),
                ('arm_weight', models.FloatField(default=0.0)),
                ('arm_speed', models.TextField(max_length=20)),
                ('arm_rechargetime', models.IntegerField(null=True)),
                ('arm_assessment', models.IntegerField(null=True)),
                ('arm_description', models.TextField(max_length=280, null=True)),
                ('arm_picture', models.TextField(null=True)),
                ('arm_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.category')),
            ],
        ),
        migrations.CreateModel(
            name='orderdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='carrito.order')),
                ('order_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.weapon')),
            ],
        ),
    ]
