# Generated by Django 3.2.7 on 2021-11-11 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.TextField(default='default', verbose_name=20)),
            ],
        ),
        migrations.CreateModel(
            name='detallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default='NOW()')),
                ('order_state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_nombre', models.TextField(max_length=20)),
                ('arm_precio', models.FloatField(default=0.0)),
                ('arm_origen', models.TextField(max_length=20)),
                ('arm_calibre', models.TextField(max_length=20)),
                ('arm_capacidad', models.IntegerField(null=True)),
                ('arm_peso', models.FloatField(default=0.0)),
                ('arm_velocidad', models.TextField(max_length=20)),
                ('arm_tiemporecarga', models.IntegerField(null=True)),
                ('arm_valoracion', models.IntegerField(null=True)),
                ('arm_descripcion', models.TextField(max_length=280, null=True)),
                ('arm_foto', models.TextField(null=True)),
                ('arm_catergoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.category')),
            ],
        ),
    ]
