# Generated by Django 3.2.7 on 2021-11-11 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='articulo_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.weapon'),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.order'),
        ),
    ]
